language: go
go_import_path: github.com/ethereum/go-ethereum
sudo: false
services:
  - docker
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      go: 1.9.x
      script:
        - sudo modprobe fuse
        - sudo chmod 666 /dev/fuse
        - sudo chown root:$USER /etc/fuse.conf
        - go run build/ci.go install
        - go run build/ci.go test -coverage $TEST_PACKAGES

after_success:
  - docker --version
  - docker build . -f Dockerfile --label "commit=$TRAVIS_COMMIT" -t $TRAVIS_COMMIT
  - docker run -d -it $TRAVIS_COMMIT
